# Generated by Django 4.2.4 on 2023-08-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
